const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=600&h=750&fit=crop`;

export const DEMO_BROWSE_PROFILES = [
  {
    profileId: 'p1',
    firstName: 'שרה',
    lastName: 'כהן',
    city: 'jerusalem',
    heightCm: 165,
    religiousStream: 'modern-haredi',
    gender: 'female',
    maritalStatus: 'single',
    age: 24,
    personalityTraits: ['חם/ה', 'אחריות', 'צנוע/ה'],
    hobbies: ['קריאה', 'טיולים', 'לימוד תורה'],
    familyVision:
      'מחפשת בית חם עם ערכי תורה, אווירה תומכת ומשפחה מלוכדת. חשוב לי חינוך לילדים בסביבה יהודית.',
    lookingFor: ['ערכים דומים', 'לימוד תורה', 'משפחה חמה'],
    references: [
      { id: 'r1-1', name: 'רבקה כהן', phoneNumber: '052-1234567', countryCode: '+972' },
    ],
    photos: [img('1494790108377-be9c29b29330'), img('1517841905240-472988babdf9')],
  },
  {
    profileId: 'p2',
    firstName: 'רבקה',
    lastName: 'לוי',
    city: 'bnei-brak',
    heightCm: 160,
    religiousStream: 'haredi',
    gender: 'female',
    maritalStatus: 'single',
    age: 22,
    personalityTraits: ['רציני/ת', 'צנוע/ה', 'אמפתי/ת'],
    hobbies: ['בישול', 'התנדבות', 'משפחה'],
    familyVision: 'בית מלא חסד, עם דגש על מסורת וצניעות.',
    lookingFor: ['צניעות', 'ערכים דומים', 'אחריות'],
    references: [{ id: 'r2-1', name: 'יעל לוי', phoneNumber: '058-1112233', countryCode: '+972' }],
    photos: [img('1438761681033-6461ffad8d80')],
  },
  {
    profileId: 'p3',
    firstName: 'מירי',
    lastName: 'גולדשטיין',
    city: 'modiin',
    heightCm: 168,
    religiousStream: 'dati-leumi',
    gender: 'female',
    maritalStatus: 'single',
    age: 26,
    personalityTraits: ['יצירתי/ת', 'שמח/ה', 'חברותי/ת'],
    hobbies: ['אמנות', 'מוזיקה', 'טיולים'],
    familyVision: 'משפחה עם אהבה, צחוק וערכים.',
    lookingFor: ['הומור', 'משפחה חמה', 'חברות טובה'],
    references: [
      { id: 'r3-1', name: 'דוד גולדשטיין', phoneNumber: '050-3344556', countryCode: '+972' },
    ],
    photos: [img('1544005313-94ddf0286df2')],
    addedByShadchan: true,
  },
  {
    profileId: 'p4',
    firstName: 'חנה',
    lastName: 'פרידמן',
    city: 'petah-tikva',
    heightCm: 163,
    religiousStream: 'modern-haredi',
    gender: 'female',
    maritalStatus: 'single',
    age: 23,
    personalityTraits: ['אחריות', 'מאורגן/ת', 'רגוע/ה'],
    hobbies: ['קריאה', 'ספורט', 'לימוד תורה'],
    familyVision: 'בית יציב עם דגש על חינוך ותמיכה הדדית.',
    lookingFor: ['יציבות כלכלית', 'חינוך לילדים', 'לימוד תורה'],
    references: [
      { id: 'r4-1', name: 'שרה פרידמן', phoneNumber: '052-7788990', countryCode: '+972' },
    ],
    photos: [img('1534528741775-53994a69daeb')],
    addedByShadchan: true,
  },
  {
    profileId: 'p5',
    firstName: 'יעל',
    lastName: 'רוזנברג',
    city: 'haifa',
    heightCm: 170,
    religiousStream: 'dati-leumi',
    gender: 'female',
    maritalStatus: 'single',
    age: 25,
    personalityTraits: ['חם/ה', 'אנרגטי/ת', 'אמפתי/ת'],
    hobbies: ['טבע', 'טיולים', 'צילום'],
    familyVision: 'משפחה שאוהבת ארץ ישראל, טיולים וזמן איכות יחד.',
    lookingFor: ['עלייה לארץ', 'משפחה חמה', 'ערכים דומים'],
    references: [
      { id: 'r5-1', name: 'מיכל רוזנברג', phoneNumber: '054-2211334', countryCode: '+972' },
    ],
    photos: [img('1517841905240-472988babdf9')],
  },
  {
    profileId: 'p6',
    firstName: 'תמר',
    lastName: 'אברהם',
    city: 'ashdod',
    heightCm: 158,
    religiousStream: 'sephardi-haredi',
    gender: 'female',
    maritalStatus: 'single',
    age: 21,
    personalityTraits: ['צנוע/ה', 'שמח/ה', 'אחריות'],
    hobbies: ['התנדבות', 'משפחה', 'בישול'],
    familyVision: 'בית מכבד מסורת ספרדית עם חום וכבוד להורים.',
    lookingFor: ['צניעות', 'משפחה חמה', 'רוחניות'],
    references: [{ id: 'r6-1', name: 'רחל אברהם', phoneNumber: '050-9988776', countryCode: '+972' }],
    photos: [img('1524504388940-b1c1722653e1')],
  },
] as const;

export const DEMO_PERSON_PROFILE = {
  profileId: 'person-me',
  firstName: 'יוסי',
  lastName: 'כהן',
  city: 'modiin',
  heightCm: 178,
  religiousStream: 'dati-leumi',
  gender: 'male' as const,
  maritalStatus: 'single',
  age: 27,
  personalityTraits: ['אחריות', 'חם/ה', 'רציני/ת'],
  hobbies: ['לימוד תורה', 'טיולים', 'ספורט'],
  familyVision:
    'מחפש בית ישראלי חם, עם דגש על תורה, משפחה וצמיחה משותפת.',
  lookingFor: ['ערכים דומים', 'לימוד תורה', 'משפחה חמה', 'אחריות'],
  references: [
    { id: 'my-ref-1', name: 'אברהם כהן', phoneNumber: '052-1112233', countryCode: '+972' },
    { id: 'my-ref-2', name: 'משה לוי', phoneNumber: '054-9988776', countryCode: '+972' },
  ],
  photos: [img('1472099645785-5658abf4ff4e')],
};
